### PR TITLE
Preparation for tang test suite using common lib

### PR DESCRIPTION
**Pull request by Koncpa**
Tang test suite will be use partialy functions from common library due to decreasing duplicity of functions for similar test suites. Needed to clear actual function script and adjust each test to use ocpop lib.

### CODE REVIEW

**Comment by Koncpa** [comment]
Need to wait for merging https://github.com/RedHat-SP-Security/common-cloud-orchestration/pull/20 .

**Comment by sarroutbi** [comment]
@Koncpa: **Please hold this until we re-release the new version (due to "latest" channel issue)**

**Comment by Koncpa** [comment]
> @Koncpa: **Please hold this until we re-release the new version (due to "latest" channel issue)**

@sarroutbi Sure, but these changes shouldn't be affected be this issue, but I'll wait, just take a look in meantime.

**Review by sarroutbi — APPROVED** [review]
Changes LGTM

**Pull request merged**
