### PR TITLE
Fix some issues reported by shellcheck

### PR DESCRIPTION
**Pull request by sarroutbi**

### CODE REVIEW

**Comment by Koncpa** [comment]
@sarroutbi Please could you wait until we merge my PR's, it should resolved these failures.. Thanks

**Comment by sarroutbi** [comment]
> @sarroutbi Please could you wait until we merge my PR's, it should resolved these failures.. Thanks

Hello Patrik. Which is the corresponding PR for this to be fixed? Are you waiting something from my side?

**Comment by Koncpa** [comment]
This is corresponding PR https://github.com/RedHat-SP-Security/tang-operator-tests/pull/83  and here we wait for new release.

**Comment by sarroutbi** [comment]
> This is corresponding PR #83 and here we wait for new release.

OK. Thanks for clarifying

**Comment by sarroutbi** [comment]
Closing. It makes no sense as some of this functions are not there any more

**Pull request closed without merging**
